### ISSUE TITLE
Titel is nog niet goed

### ISSUE THREAD

**Issue by hiddebraun-ma** [hiddebraun-ma/git-intro#1]
https://github.com/hiddebraun-ma/git-intro/blob/0f44df6a33a69d1ddbc58bf8e2e9e4a8a5518d76/index.html#L6

**Comment by bobvberckel** [comment]
Dit is nu aangepast naar `Git Intro - 1`.

Sorry dat ik zo laat reageer, ik krijg hier geen meldingen van binnen ofzo?

**Comment by hiddebraun-ma** [comment]
No problem, ik wilde even checken of het werken met die issues te doen is.
En volgens mij werkt he.
